// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transformers_battle_sim.Data.Impl;

namespace transformers_battle_sim.Migrations
{
    [DbContext(typeof(TransformerRepository))]
    [Migration("20240616210532_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("transformers_battle_sim.Models.Transformer.Impl.Mode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AttackPower")
                        .HasColumnType("float");

                    b.Property<string>("ModeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MovementSpeed")
                        .HasColumnType("float");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransformerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransformerId");

                    b.ToTable("Mode");
                });

            modelBuilder.Entity("transformers_battle_sim.Models.Transformer.Impl.Transformer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Faction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LossCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transformer");
                });

            modelBuilder.Entity("transformers_battle_sim.Models.Transformer.Impl.Mode", b =>
                {
                    b.HasOne("transformers_battle_sim.Models.Transformer.Impl.Transformer", null)
                        .WithMany("Modes")
                        .HasForeignKey("TransformerId");
                });
#pragma warning restore 612, 618
        }
    }
}
